
# This file can be used with the REST Client VSCode Extension
# @see https://marketplace.visualstudio.com/items?itemName=humao.rest-client

#################################################################################

@apiBasePath = http://localhost:8080
# @apiBasePath = https://ord-reference-application.cfapps.sap.hana.ondemand.com/

# TenantIDs for Tenant T1
@localTenantId = T1
@sapGlobalTenantId = 740000101
@apiAuthorization = Basic Zm9vOmJhcg==

# TenantIDs for Tenant T2
# @localTenantId = T2
# @sapGlobalTenantId = 740000102


#################################################################################

# First step:
# * Discovery the whether ORD is supported by the system instance
# * Find out which version of ORD and which capabilities are supported
# * Find out which ORD documents are available and where they are stored
GET {{apiBasePath}}/.well-known/open-resource-discovery HTTP/1.1
content-type: application/json

#################################################################################

# Second Step (1/2)
# * REPEAT for each discovered ORD Document:
#   * GET the ORD document according to the `accessType` (here: `open`)
GET {{apiBasePath}}/open-resource-discovery/v1/documents/system-version HTTP/1.1
content-type: application/json

#################################################################################

# Second Step (2/2)
# * REPEAT for each discovered ORD Document:
#   * GET the ORD document according to the `accessType` (here: `basic-auth`)
#   * The authenticated user determines the tenant / system instance.
GET {{apiBasePath}}/open-resource-discovery/v1/documents/system-instance HTTP/1.1
content-type: application/json
Authorization: {{apiAuthorization}}

#################################################################################

# Third Step (1/2)
# * REPEAT for each discovered and relevant resource definition:
#   * GET the resource definition file according to the `accessType` (here: `open`)
GET {{apiBasePath}}/astronomy/v1/openapi/oas3.json HTTP/1.1
content-type: application/json
#################################################################################

# Third Step (2/2)
# * REPEAT for each discovered and relevant resource definition:
#   * GET the resource definition file according to the `accessType` (here: `custom`)
GET {{apiBasePath}}/crm/v1/openapi/oas3.json HTTP/1.1
content-type: application/json
global-tenant-id: {{sapGlobalTenantId}}

#################################################################################

# Follow Up
# Now that we have discovered that we have an Astronomy API
# and where / how it is accessed at run-time.

GET {{apiBasePath}}/astronomy/v1/constellations HTTP/1.1
content-type: application/json

#################################################################################

# Addon: RECOMMENDED ETags
# If we send the ETag from a previous request and no changes have been done
# We should get a 304 Not Modified Response
GET {{apiBasePath}}/.well-known/open-resource-discovery HTTP/1.1
content-type: application/json
If-None-Match: "1wzy420"
