name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: npm

      - name: Install NPM dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Biome
        run: npm run check

      - name: Test
        run: npm run test:ci
